name: CustomHeads
version: 1.1
api-version: 1.13
author: Vannername
main: me.vannername.customheads.Main
description: My own plugin which allows to store and get custom heads.
commands:
  heads:
    permission: vanyaplugin.heads